//! Kraskus solo endpoint for `cmfd-node run` (Kraskus-Common-Foundry-Solo).
//!
//! NOT UPSTREAM. This module is the whole Kraskus change apart from the small
//! hook in `main.rs`. It serves the unmodified upstream pool protocol from the
//! normal `run` mode (P2P, loopback RPC, wallet and explorer stay up) through the
//! unmodified `spawn_pool_server`, configured for one solo operator:
//!
//! - the block reward pays the operator's own address (the node wallet by
//!   default), with no payout ledger, no PPLNS and no payout transactions;
//! - the share target is the network target, so only block-winning nonces are
//!   submitted, replayed and proven by the official ProductionV4 workers;
//! - the endpoint only listens once those workers have started and reported
//!   ready. Until then miners cannot connect and no jobs are handed out.
//!
//! Consensus, the PoW algorithm, block assembly and the wire protocol are the
//! upstream code paths, unchanged.

use std::error::Error;
use std::fs;
use std::io::Write;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

use clap::Args;
use cmfd_node::pool::{PoolServerConfig, PoolServerHandle, certificate_sha256, spawn_pool_server};
use cmfd_node::pool_dashboard::{PoolDashboardConfig, PoolDashboardHandle, spawn_pool_dashboard};
use cmfd_node::{Node, ProductionV4VerifierArtifacts, parse_miner_destination, unix_time_seconds};
use serde_json::{Value, json};

/// `--version` names the Kraskus build so it is never mistaken for the
/// official upstream binary of the same release.
pub const VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), "+kraskus-solo.1");

pub const SOLO_STATUS_SCHEMA: &str = "KRASKUS_CMFD_SOLO_STATUS_V1";

/// The hardest possible target. `spawn_pool_server` uses the easier of the
/// configured and chain targets, so this yields exactly the network target.
pub const SOLO_SHARE_TARGET: [u8; 32] = [0; 32];

#[derive(Debug, Clone, Default, Args)]
pub struct SoloPoolArgs {
    /// Kraskus solo: serve the pool protocol for solo mining from `run` on this
    /// private (LAN or loopback) address. Off unless supplied.
    #[arg(long, requires_all = ["solo_pool_certificate", "solo_pool_private_key"])]
    pub solo_pool_bind: Option<SocketAddr>,
    /// DER certificate generated by pool-certificate.
    #[arg(long, requires = "solo_pool_bind")]
    pub solo_pool_certificate: Option<PathBuf>,
    /// DER PKCS#8 private key generated by pool-certificate.
    #[arg(long, requires = "solo_pool_bind")]
    pub solo_pool_private_key: Option<PathBuf>,
    /// 64-hex block-reward destination; defaults to the node wallet.
    #[arg(long, requires = "solo_pool_bind")]
    pub solo_pool_miner: Option<String>,
    /// Absolute path to the official ProductionV4 replay worker.
    #[arg(long, requires = "solo_pool_bind")]
    pub solo_pool_replay_worker: Option<PathBuf>,
    /// Absolute path to the official ProductionV4 proof worker.
    #[arg(long, requires = "solo_pool_bind")]
    pub solo_pool_proof_worker: Option<PathBuf>,
    /// Absolute scratch directory shared by the two workers.
    #[arg(long, requires = "solo_pool_bind")]
    pub solo_pool_scratch: Option<PathBuf>,
    /// Status JSON rewritten on every state change (schema KRASKUS_CMFD_SOLO_STATUS_V1).
    #[arg(long, requires = "solo_pool_bind")]
    pub solo_pool_status_file: Option<PathBuf>,
    /// Seconds between attempts to start the workers when they are unavailable.
    #[arg(long, default_value_t = 60, requires = "solo_pool_bind")]
    pub solo_pool_retry_seconds: u64,
    /// Loopback address for the upstream read-only pool dashboard (`/api/v1/pool`).
    #[arg(long, requires_all = ["solo_pool_bind", "solo_pool_dashboard_assets", "solo_pool_public_url"])]
    pub solo_pool_dashboard_bind: Option<SocketAddr>,
    /// Upstream dashboard asset directory.
    #[arg(long, requires = "solo_pool_dashboard_bind")]
    pub solo_pool_dashboard_assets: Option<PathBuf>,
    /// cmfd+tls URL shown by the dashboard; its pin must match the certificate.
    #[arg(long, requires = "solo_pool_dashboard_bind")]
    pub solo_pool_public_url: Option<String>,
}

#[derive(Default)]
struct Services {
    pool: Option<PoolServerHandle>,
    dashboard: Option<PoolDashboardHandle>,
}

/// Background owner of the solo endpoint. The node keeps running whatever the
/// endpoint state is; only a crash of a started endpoint ends the process,
/// exactly as `pool-serve` treats its own pool thread.
pub struct SoloPool {
    stop: Arc<AtomicBool>,
    services: Arc<Mutex<Services>>,
    supervisor: Option<JoinHandle<()>>,
    status: StatusWriter,
}

impl SoloPool {
    pub fn startup_json(&self) -> Value {
        self.status.current()
    }

    pub fn is_finished(&self) -> bool {
        self.services.lock().is_ok_and(|services| {
            services
                .pool
                .as_ref()
                .is_some_and(PoolServerHandle::is_finished)
                || services
                    .dashboard
                    .as_ref()
                    .is_some_and(PoolDashboardHandle::is_finished)
        })
    }

    pub fn stop(mut self) -> Result<(), Box<dyn Error>> {
        self.stop.store(true, Ordering::Release);
        if let Some(supervisor) = self.supervisor.take() {
            let _ = supervisor.join();
        }
        let services = std::mem::take(
            &mut *self
                .services
                .lock()
                .map_err(|_| "solo pool state poisoned")?,
        );
        let dashboard = services.dashboard.map(PoolDashboardHandle::stop);
        let pool = services.pool.map(PoolServerHandle::stop);
        self.status.update("stopped", None, None);
        if let Some(result) = dashboard {
            result?;
        }
        if let Some(result) = pool {
            result?;
        }
        Ok(())
    }
}

/// Validates the static options and starts the endpoint supervisor. Returns
/// `Ok(None)` when `--solo-pool-bind` is absent (upstream behaviour).
pub fn spawn(
    args: SoloPoolArgs,
    node: Arc<Mutex<Node>>,
    artifacts: Option<ProductionV4VerifierArtifacts>,
) -> Result<Option<SoloPool>, Box<dyn Error>> {
    let Some(bind) = args.solo_pool_bind else {
        return Ok(None);
    };
    let certificate_der = fs::read(args.solo_pool_certificate.as_ref().ok_or("certificate")?)?;
    let private_key_der = fs::read(args.solo_pool_private_key.as_ref().ok_or("private key")?)?;
    let pin = certificate_sha256(&certificate_der);
    let destination = match args.solo_pool_miner.as_deref() {
        Some(value) => parse_miner_destination(value)?,
        None => node
            .lock()
            .map_err(|_| "shared node poisoned")?
            .wallet_destination(),
    };
    if args.solo_pool_retry_seconds == 0 {
        return Err("solo-pool-retry-seconds must be at least 1".into());
    }
    let status = StatusWriter::new(
        args.solo_pool_status_file.clone(),
        json!({
            "schema": SOLO_STATUS_SCHEMA,
            "endpoint": bind.to_string(),
            "certificate_sha256": hex::encode(pin),
            "block_reward_destination": hex::encode(destination),
            "share_target": "network",
            "payouts": "none (solo: the block reward pays the destination directly)",
        }),
    );
    status.update("starting", None, None);
    let stop = Arc::new(AtomicBool::new(false));
    let services = Arc::new(Mutex::new(Services::default()));
    let supervisor = {
        let stop = Arc::clone(&stop);
        let services = Arc::clone(&services);
        let status = status.clone();
        thread::Builder::new()
            .name("kraskus-solo-pool".to_owned())
            .spawn(move || {
                let retry = Duration::from_secs(args.solo_pool_retry_seconds);
                let mut attempt = 0_u64;
                while !stop.load(Ordering::Acquire) {
                    attempt += 1;
                    match start_services(
                        &args,
                        bind,
                        &certificate_der,
                        &private_key_der,
                        pin,
                        destination,
                        &node,
                        artifacts.as_ref(),
                    ) {
                        Ok((pool, dashboard)) => {
                            let address = pool.local_addr().to_string();
                            let dashboard_address = dashboard
                                .as_ref()
                                .map(|dashboard| format!("http://{}", dashboard.local_addr()));
                            if let Ok(mut held) = services.lock() {
                                held.pool = Some(pool);
                                held.dashboard = dashboard;
                            }
                            status.update(
                                "ready",
                                None,
                                Some(json!({
                                    "listening": address,
                                    "dashboard": dashboard_address,
                                    "attempts": attempt,
                                })),
                            );
                            eprintln!("kraskus solo pool: ready on {address}");
                            return;
                        }
                        Err(error) => {
                            let message = error.to_string();
                            eprintln!(
                                "kraskus solo pool: prover not ready (attempt {attempt}): {message}"
                            );
                            status.update(
                                "prover_unavailable",
                                Some(message),
                                Some(
                                    json!({"attempts": attempt, "retry_seconds": retry.as_secs()}),
                                ),
                            );
                        }
                    }
                    let deadline = Instant::now() + retry;
                    while Instant::now() < deadline && !stop.load(Ordering::Acquire) {
                        thread::sleep(Duration::from_millis(250));
                    }
                }
            })?
    };
    Ok(Some(SoloPool {
        stop,
        services,
        supervisor: Some(supervisor),
        status,
    }))
}

#[allow(clippy::too_many_arguments)]
fn start_services(
    args: &SoloPoolArgs,
    bind: SocketAddr,
    certificate_der: &[u8],
    private_key_der: &[u8],
    pin: [u8; 32],
    destination: [u8; 32],
    node: &Arc<Mutex<Node>>,
    artifacts: Option<&ProductionV4VerifierArtifacts>,
) -> Result<(PoolServerHandle, Option<PoolDashboardHandle>), Box<dyn Error>> {
    let config = solo_pool_config(
        bind,
        certificate_der.to_vec(),
        private_key_der.to_vec(),
        destination,
    );
    let mut config = config;
    // Upstream helper: the same official worker commands `pool-serve` uses.
    crate::configure_production_v4_pool_verifier(
        &mut config,
        artifacts,
        args.solo_pool_replay_worker.as_ref(),
        args.solo_pool_proof_worker.as_ref(),
        args.solo_pool_scratch.as_ref(),
        None,
    )?;
    let pool = spawn_pool_server(Arc::clone(node), config)?;
    let dashboard = match (
        args.solo_pool_dashboard_bind,
        args.solo_pool_dashboard_assets.as_ref(),
        args.solo_pool_public_url.as_ref(),
    ) {
        (Some(dashboard_bind), Some(assets), Some(public_url)) => Some(spawn_pool_dashboard(
            pool.dashboard_source(),
            PoolDashboardConfig {
                bind: dashboard_bind,
                assets_directory: assets.clone(),
                public_pool_url: public_url.clone(),
                certificate_sha256: pin,
            },
        )?),
        _ => None,
    };
    Ok((pool, dashboard))
}

/// The solo configuration of the unmodified upstream pool server.
pub fn solo_pool_config(
    bind: SocketAddr,
    certificate_der: Vec<u8>,
    private_key_der: Vec<u8>,
    destination: [u8; 32],
) -> PoolServerConfig {
    let mut config = PoolServerConfig::devnet(bind, certificate_der, private_key_der, destination);
    config.share_target = SOLO_SHARE_TARGET;
    config.test_credit_atoms_per_share = 0;
    config.ledger_directory = None;
    config.payout_policy = None;
    config.pplns_policy = None;
    config.allow_public_clients = false;
    config.allow_address_only_payouts = false;
    config
}

#[derive(Clone)]
struct StatusWriter {
    path: Option<PathBuf>,
    document: Arc<Mutex<Value>>,
}

impl StatusWriter {
    fn new(path: Option<PathBuf>, base: Value) -> Self {
        Self {
            path,
            document: Arc::new(Mutex::new(base)),
        }
    }

    fn current(&self) -> Value {
        self.document
            .lock()
            .map(|document| document.clone())
            .unwrap_or(Value::Null)
    }

    fn update(&self, state: &str, error: Option<String>, detail: Option<Value>) {
        let Ok(mut document) = self.document.lock() else {
            return;
        };
        let object = document
            .as_object_mut()
            .expect("status document is an object");
        object.insert("state".to_owned(), json!(state));
        object.insert("error".to_owned(), json!(error));
        object.insert("detail".to_owned(), detail.unwrap_or(Value::Null));
        object.insert(
            "updated_unix".to_owned(),
            json!(unix_time_seconds().unwrap_or(0)),
        );
        if let Some(path) = &self.path
            && let Err(error) = write_atomically(path, &document)
        {
            eprintln!("kraskus solo pool: status file not written: {error}");
        }
    }
}

fn write_atomically(path: &Path, document: &Value) -> Result<(), Box<dyn Error>> {
    let temporary = path.with_extension("json.tmp");
    {
        let mut file = fs::File::create(&temporary)?;
        file.write_all(&serde_json::to_vec_pretty(document)?)?;
        file.write_all(b"\n")?;
        file.sync_all()?;
    }
    fs::rename(&temporary, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use cmfd_consensus::forgematrix::target_with_leading_zero_bits;

    fn config() -> PoolServerConfig {
        solo_pool_config("127.0.0.1:0".parse().unwrap(), vec![1], vec![2], [7; 32])
    }

    #[test]
    fn solo_config_has_no_payout_accounting() {
        let config = config();
        assert!(config.payout_policy.is_none());
        assert!(config.pplns_policy.is_none());
        assert!(config.ledger_directory.is_none());
        assert_eq!(config.test_credit_atoms_per_share, 0);
        assert!(!config.allow_public_clients);
        assert!(!config.allow_address_only_payouts);
        assert_eq!(config.block_destination, [7; 32]);
    }

    #[test]
    fn solo_share_target_resolves_to_the_chain_target() {
        // spawn_pool_server takes max(configured, chain): the easier target.
        let config = config();
        for bits in [0_u16, 8, 20, 64, 255] {
            let chain = target_with_leading_zero_bits(bits);
            assert_eq!(config.share_target.max(chain), chain);
        }
    }

    #[test]
    fn status_file_is_written_atomically() {
        let directory = std::env::temp_dir().join(format!(
            "kraskus-solo-status-{}-{}",
            std::process::id(),
            unix_time_seconds().unwrap()
        ));
        fs::create_dir_all(&directory).unwrap();
        let path = directory.join("solo.json");
        let writer = StatusWriter::new(Some(path.clone()), json!({"schema": SOLO_STATUS_SCHEMA}));
        writer.update("prover_unavailable", Some("no GPU".to_owned()), None);
        let value: Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
        assert_eq!(value["state"], "prover_unavailable");
        assert_eq!(value["error"], "no GPU");
        assert_eq!(value["schema"], SOLO_STATUS_SCHEMA);
        assert!(!path.with_extension("json.tmp").exists());
        fs::remove_dir_all(directory).unwrap();
    }

    /// End to end on the in-process DevNet reference profile: the unmodified
    /// pool client mines through the solo configuration, every share it can
    /// submit is a block, the block is accepted, the reward pays the node
    /// wallet and no payout ledger is written.
    #[test]
    fn solo_endpoint_mines_a_devnet_block_to_the_node_wallet() {
        use cmfd_node::DEVNET_PROFILE;
        use cmfd_node::pool::{
            PoolClient, PoolClientConfig, PoolPayoutSigner, PoolWorkSearchResult,
            generate_pool_certificate,
        };
        use k256::schnorr::SigningKey;

        let mut id = [0_u8; 16];
        getrandom::fill(&mut id).unwrap();
        let root = std::env::temp_dir().join(format!("kraskus-solo-e2e-{}", hex::encode(id)));
        fs::create_dir(&root).unwrap();
        let data = root.join("node");
        let node = Arc::new(Mutex::new(
            Node::open_with_profile(&data, DEVNET_PROFILE).unwrap(),
        ));
        let destination = node.lock().unwrap().wallet_destination();
        let immature_before = node
            .lock()
            .unwrap()
            .wallet_snapshot()
            .unwrap()
            .immature_utxo_count;
        let certificate = root.join("solo.crt.der");
        let key = root.join("solo.key.der");
        let pin = generate_pool_certificate(&certificate, &key)
            .unwrap()
            .certificate_sha256;
        let server = spawn_pool_server(
            Arc::clone(&node),
            solo_pool_config(
                "127.0.0.1:0".parse().unwrap(),
                fs::read(&certificate).unwrap(),
                fs::read(&key).unwrap(),
                destination,
            ),
        )
        .unwrap();

        let signer = PoolPayoutSigner::new(SigningKey::from_bytes(&[0x13; 32]).unwrap());
        let mut client = PoolClient::connect(
            PoolClientConfig::devnet(server.local_addr(), pin, "solo-e2e", signer).unwrap(),
        )
        .unwrap();
        let work = client.current_work().unwrap();
        assert_eq!(work.job().share_target, work.job().challenge.target);
        let height = work.job().challenge.height;
        let mut next = 0;
        let nonce = loop {
            match work.search_range(next, 1_000, || false).unwrap() {
                PoolWorkSearchResult::Found {
                    nonce,
                    meets_chain_target,
                    ..
                } => {
                    assert!(meets_chain_target, "solo shares are blocks only");
                    break nonce;
                }
                PoolWorkSearchResult::Exhausted { next_nonce, .. } => next = next_nonce,
                PoolWorkSearchResult::Cancelled { .. } => unreachable!(),
            }
        };
        let result = client.submit_share(work.job().job_id, nonce).unwrap();
        assert!(result.accepted);
        assert!(result.block_accepted);
        assert_eq!(result.code, "block_accepted");
        {
            let mut node = node.lock().unwrap();
            assert_eq!(node.status().unwrap().accepted_height, height);
            assert!(node.wallet_snapshot().unwrap().immature_utxo_count > immature_before);
        }
        drop(client);
        server.stop().unwrap();
        assert!(!data.join("pool-ledger").exists());
        drop(node);
        let _ = fs::remove_dir_all(root);
    }
}
